<< -----get nuclear data----- >>
CLOBBER
JSON
MONITOR 1
LIBVERSION 1
GETXS 0
GETDECAY 0
FISPACT
* IRRADIATION OF TI EEF FW 1.0 MW/M2
<< -----set initial conditions----- >>
MASS 1.0 1
Ti 100.0
MIND 1.E5
NUCGRAPH 7 0.01  1 1 2 3 4 5 6 7 
WALL 1.00
UNCERT 1
ATOMS
HAZA 
HALF 
ATWO
DOSE 1 
<< -----irradiation phase----- >>
TIME 2.5 YEARS 
ATOMS
<< -----cooling phase----- >>
FLUX 0.
ZERO
TIME 1 MINS ATOMS
TIME 1 HOURS ATOMS
TIME 1 DAYS ATOMS
TIME 7 DAYS ATOMS
TIME 30 DAYS ATOMS
TIME 1 YEARS ATOMS
TIME 3 YEARS ATOMS
TIME 10 YEARS ATOMS
TIME 30 YEARS ATOMS
TIME 100 YEARS ATOMS
TIME 300 YEARS ATOMS
TIME 1000 YEARS ATOMS
END
* END
