<< -----get nuclear data----- >>
MONITOR 1
GETXS 0
GETDECAY 0
FISPACT
* IRRADIATION OF Fe EEF 175 FW 1.0 MW/M2
<< -----set initial conditions----- >>
MASS 1.0 1
Fe 100.0
MIND 1.E5
WALL 1.00
ATOMS
HAZA
HALF
ATWO
UNCERT 2
SORTDOM 10 5
<< -----irradiation phase----- >>
TIME 2.5 YEARS
ATOMS
PULSE 2
 PULSE 2
  FLUX 0.
  TIME 1.0 HOUR SPECTRUM
  WALL 1.0
  TIME 1.0 HOUR SPECTRUM
 ENDPULSE
ENDPULSE
   FLUX 0.
  TIME 1.0 HOUR SPECTRUM
   WALL 1.0
  TIME 1.0 HOUR SPECTRUM
FLUX 0.
TIME 1.0 HOUR SPECTRUM
WALL 1.0
TIME 1.0 HOUR ATOMS
<< -----cooling phase----- >>
FLUX 0.0
ZERO
TIME 1 MINS ATOMS
TIME 1 HOURS ATOMS
TIME 1 DAYS ATOMS
TIME 7 DAYS ATOMS
TIME 1 YEARS ATOMS
END
* END

