<< -----get nuclear data----- >>
CLOBBER
<< LIBVERSION 0 >>
GETXS 0 
GETDECAY 0
FISPACT
* IRRADIATION OF TI EEF FW 1.0 MW/M2
<< -----set initial conditions----- >>
MASS 1.0 1
Ti 100.0
MIND 1.E5
NUCGRAPH 7 0.01  1 1 2 3 4 5 6 7 
WALL 1.00
UNCERT 1
ATOMS
HAZA 
HALF 
ATWO
DOSE 1 
<< -----irradiation phase----- >>
TIME 2.5 YEARS 
ATOMS
<< -----cooling phase----- >>
FLUX 0.
ZERO
TIME 1e-20 ATOMS	
TIME 1.0 ATOMS	
TIME 299 ATOMS
TIME 25 MINS ATOMS
TIME 30 MINS ATOMS
TIME 2 HOURS ATOMS
TIME 2 HOURS ATOMS
TIME 5 HOURS ATOMS
TIME 14 HOURS ATOMS
TIME 2 DAYS ATOMS
TIME 4 DAYS ATOMS
TIME 7 DAYS ATOMS
TIME 14 DAYS ATOMS
TIME 28 DAYS ATOMS
TIME 126 DAYS ATOMS
TIME 183.25 DAYS ATOMS
TIME 4 YEARS ATOMS
TIME 5 YEARS ATOMS
PULSE 9
TIME 10 YEARS ATOMS
ENDPULSE
PULSE 9
TIME 100 YEARS ATOMS
ENDPULSE
END
* END
